# Lists

In [1]:
#--- Allows multitype data items
MyFirstList = [3, 45, 8.5, 20, 'John', True]
MyFirstList

[3, 45, 8.5, 20, 'John', True]

In [2]:
type(MyFirstList)

list

### Create list using range()

In [3]:
x = list(range(10))
y = list(range(10, 25, 2))

In [4]:
# This will show the result of the last line only
x
y

[10, 12, 14, 16, 18, 20, 22, 24]

In [5]:
# use print() to print multiple outputs from a single cell
print(x)
print(y)
print(min(x))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[10, 12, 14, 16, 18, 20, 22, 24]
0


### Getting a value by index

In [6]:
print(y[0])
print(y[len(y)-2])
print(x[-2])

10
22
8


### List Slicing

In [7]:
print (y[:])
print (y[:2])
print (y[3:5])
print (y[4:])
print (y[-8:5])
print (x[2:8:3]) #--- [Start, End, Step]
print (x[::3])
print (x[::-2])
print (x[7:2:-2])

[10, 12, 14, 16, 18, 20, 22, 24]
[10, 12]
[16, 18]
[18, 20, 22, 24]
[10, 12, 14, 16, 18]
[2, 5]
[0, 3, 6, 9]
[9, 7, 5, 3, 1]
[7, 5, 3]


### Get unique values

In [8]:
z = [1,1,1,2,2,2,4,4,4,3,3,3]
z

[1, 1, 1, 2, 2, 2, 4, 4, 4, 3, 3, 3]

In [9]:
set(z)

{1, 2, 3, 4}

# Tuple

### Tuple = Immutable List --> Can't change the values once defined

In [10]:
t1 = (1, 3, 6, 9)
print(t1)
print (t1[2])

(1, 3, 6, 9)
6


In [11]:
print (type(t1))
print ("Minimum value is {}, Maximum value is {}".format(min(t1),max(t1)))

<class 'tuple'>
Minimum value is 1, Maximum value is 9


# Array

In [12]:
import numpy as np

### List to Array

In [13]:
a = np.array(x)                #--- Array --> Items with same data types
print(a)
print(type(a))
a

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
a.mean()

4.5

### Creating Array view and Array copy

In [15]:
b = a[2:4]    #--- Creates just a view of the original array, not a copy/new - unlike list

In [16]:
print(b)
b[0]

[2 3]


2

In [17]:
b[:] = 111

In [18]:
b

array([111, 111])

In [19]:
a

array([  0,   1, 111, 111,   4,   5,   6,   7,   8,   9])

In [20]:
c = a.copy()
c

array([  0,   1, 111, 111,   4,   5,   6,   7,   8,   9])

In [21]:
c[0] = 50
print(c)
print(b)
print(a)

[ 50   1 111 111   4   5   6   7   8   9]
[111 111]
[  0   1 111 111   4   5   6   7   8   9]


### Element wise operations

In [22]:
# --- Analyze financial statement

#Data 
revenue = [14574.49, 7606.46, 8611.41, 9175.41, 8058.65, 8105.44, 11496.28, 9766.09, 10305.32, 14379.96, 10713.97, 15433.50]
expenses = [12051.82, 5695.07, 12319.20, 12089.72, 8658.57, 840.20, 3285.73, 5821.12, 6976.93, 16618.61, 10054.37, 3803.96]

In [23]:
re = np.array(revenue)

In [24]:
ex = np.array(expenses)

In [25]:
profit = re - ex
pat = np.round((re*.3) - ex, 0)
pmargin = np.round(pat*100 / re, 2)

In [26]:
print(profit)
print(pat)
print(pmargin)

[ 2522.67  1911.39 -3707.79 -2914.31  -599.92  7265.24  8210.55  3944.97
  3328.39 -2238.65   659.6  11629.54]
[ -7679.  -3413.  -9736.  -9337.  -6241.   1591.    163.  -2891.  -3885.
 -12305.  -6840.    826.]
[ -52.69  -44.87 -113.06 -101.76  -77.44   19.63    1.42  -29.6   -37.7
  -85.57  -63.84    5.35]


In [27]:
print (min(pat), max(pat))

-12305.0 1591.0


### Matrix

In [28]:
matrix1 = np.array([range(0,10),range(10,20),range(20,30)])

In [29]:
matrix1.shape

(3, 10)

In [30]:
type(matrix1)

numpy.ndarray

### Reshape

In [31]:
matrix2 = np.array([range(0,50)])

In [32]:
matrix2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49]])

In [33]:
matrix2.reshape((5,10))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

### Dictionary

In [34]:
# Dictionaries can't be accessed by order / index, need to access by key only
dict1 = {'key1':'val1', 'key2':'val2', 'key3':'val3'}
print (dict1)
dict1['key3']

{'key1': 'val1', 'key2': 'val2', 'key3': 'val3'}


'val3'

# DataFrame

In [35]:
import pandas as pd

### Read csv - create a DF from a csv file

In [36]:
vixData = pd.read_csv('hist_india_vix_2018.csv')

In [37]:
vixData

Date     Open     High      Low    Close   Prev. Close   Change   \
0    01-Jan-2018  12.6700  13.6125  12.5450  13.3525       12.6700     0.68   
1    02-Jan-2018  13.3525  13.8425  12.6050  13.6850       13.3525     0.33   
2    03-Jan-2018  13.6850  13.7150  12.7650  13.6225       13.6850    -0.06   
3    04-Jan-2018  13.6225  13.7925  12.1825  13.4150       13.6225    -0.21   
4    05-Jan-2018  13.4150  13.4150  12.4200  13.1125       13.4150    -0.30   
..           ...      ...      ...      ...      ...           ...      ...   
241  24-Dec-2018  15.9925  17.1325  14.8975  15.7500       15.9925    -0.24   
242  26-Dec-2018  15.7500  17.4775  14.8075  15.9200       15.7500     0.17   
243  27-Dec-2018  15.9200  16.3750  12.5625  16.0725       15.9200     0.15   
244  28-Dec-2018  16.0725  16.0725  15.0150  15.2700       16.0725    -0.80   
245  31-Dec-2018  15.2700  16.1525  14.6500  16.0000       15.2700     0.73   

     % Change  
0        5.39  
1        2.49  
2       -0.46  
3       -1.52  
4       -2.25  
..        ...  
241     -1.52  
242      1.08  
243      0.96  
244     -4.99  
245      4.78  

[246 rows x 8 columns]

### Explore the data

In [38]:
# No of Rows and Columns

print(len(vixData))    #-- Rows
print(len(vixData.columns))

246
8


In [39]:
vixData.columns

Index(['Date ', 'Open ', 'High ', 'Low ', 'Close ', 'Prev. Close ', 'Change ',
       '% Change'],
      dtype='object')

In [40]:
# Top 10 rows
vixData.head(10)

Date     Open     High      Low    Close   Prev. Close   Change   \
0  01-Jan-2018  12.6700  13.6125  12.5450  13.3525       12.6700     0.68   
1  02-Jan-2018  13.3525  13.8425  12.6050  13.6850       13.3525     0.33   
2  03-Jan-2018  13.6850  13.7150  12.7650  13.6225       13.6850    -0.06   
3  04-Jan-2018  13.6225  13.7925  12.1825  13.4150       13.6225    -0.21   
4  05-Jan-2018  13.4150  13.4150  12.4200  13.1125       13.4150    -0.30   
5  08-Jan-2018  13.1125  13.8550  11.8125  13.7350       13.1125     0.62   
6  09-Jan-2018  13.7350  14.1300  12.2500  13.8475       13.7350     0.11   
7  10-Jan-2018  13.8475  14.2275  12.5175  14.0350       13.8475     0.19   
8  11-Jan-2018  14.0350  14.2775  12.9850  14.0125       14.0350    -0.02   
9  12-Jan-2018  14.0125  14.5525  11.9200  13.7325       14.0125    -0.28   

   % Change  
0      5.39  
1      2.49  
2     -0.46  
3     -1.52  
4     -2.25  
5      4.75  
6      0.82  
7      1.35  
8     -0.16  
9     -2.00

In [41]:
# Bottom 10 rows
vixData.tail(10)

Date     Open     High      Low    Close   Prev. Close   Change   \
236  17-Dec-2018  15.1575  15.9125  13.8675  14.5400       15.1575    -0.62   
237  18-Dec-2018  14.5400  15.3125  11.9825  14.5775       14.5400     0.04   
238  19-Dec-2018  14.5775  14.8650  11.8700  14.6600       14.5775     0.08   
239  20-Dec-2018  14.6600  14.9175  13.7200  14.3325       14.6600    -0.33   
240  21-Dec-2018  14.3325  16.2300  12.9400  15.9925       14.3325     1.66   
241  24-Dec-2018  15.9925  17.1325  14.8975  15.7500       15.9925    -0.24   
242  26-Dec-2018  15.7500  17.4775  14.8075  15.9200       15.7500     0.17   
243  27-Dec-2018  15.9200  16.3750  12.5625  16.0725       15.9200     0.15   
244  28-Dec-2018  16.0725  16.0725  15.0150  15.2700       16.0725    -0.80   
245  31-Dec-2018  15.2700  16.1525  14.6500  16.0000       15.2700     0.73   

     % Change  
236     -4.07  
237      0.26  
238      0.57  
239     -2.23  
240     11.58  
241     -1.52  
242      1.08  
243      0.96  
244     -4.99  
245      4.78

In [42]:
# Check the datatype of columns
vixData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 246 entries, 0 to 245
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Date          246 non-null    object 
 1   Open          246 non-null    float64
 2   High          246 non-null    float64
 3   Low           246 non-null    float64
 4   Close         246 non-null    float64
 5   Prev. Close   246 non-null    float64
 6   Change        246 non-null    float64
 7   % Change      246 non-null    float64
dtypes: float64(7), object(1)
memory usage: 15.5+ KB


In [43]:
# Get descriptive statistics
vixData.describe()

Open        High         Low       Close   Prev. Close   \
count  246.000000  246.000000  246.000000  246.000000    246.000000   
mean    15.060315   15.731352   13.309807   15.073852     15.060315   
std      2.422166    2.709494    2.382397    2.418055      2.422166   
min     11.895000   12.500000    9.430000   11.895000     11.895000   
25%     13.080625   13.645000   11.547500   13.120625     13.080625   
50%     14.255000   14.652500   12.493750   14.266250     14.255000   
75%     16.796875   17.875625   15.064375   16.796875     16.796875   
max     21.357500   24.035000   19.575000   21.357500     21.357500   

          Change     % Change  
count  246.000000  246.000000  
mean     0.023862    0.259756  
std      0.762931    4.638415  
min     -2.490000  -12.200000  
25%     -0.357500   -2.200000  
50%      0.000000    0.000000  
75%      0.337500    2.410000  
max      3.960000   24.680000

In [44]:
vixData.describe().transpose()

count       mean       std     min        25%       50%  \
Open          246.0  15.060315  2.422166  11.895  13.080625  14.25500   
High          246.0  15.731352  2.709494  12.500  13.645000  14.65250   
Low           246.0  13.309807  2.382397   9.430  11.547500  12.49375   
Close         246.0  15.073852  2.418055  11.895  13.120625  14.26625   
Prev. Close   246.0  15.060315  2.422166  11.895  13.080625  14.25500   
Change        246.0   0.023862  0.762931  -2.490  -0.357500   0.00000   
% Change      246.0   0.259756  4.638415 -12.200  -2.200000   0.00000   

                    75%      max  
Open          16.796875  21.3575  
High          17.875625  24.0350  
Low           15.064375  19.5750  
Close         16.796875  21.3575  
Prev. Close   16.796875  21.3575  
Change         0.337500   3.9600  
% Change       2.410000  24.6800

In [45]:
# Renaming columns
vixData.columns = ['c_Date', 'c_Open', 'c_High', 'c_Low', 'c_Close', 'c_PrevClose', 'c_Change','c_ChangePer']

In [46]:
vixData.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 246 entries, 0 to 245
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   c_Date       246 non-null    object 
 1   c_Open       246 non-null    float64
 2   c_High       246 non-null    float64
 3   c_Low        246 non-null    float64
 4   c_Close      246 non-null    float64
 5   c_PrevClose  246 non-null    float64
 6   c_Change     246 non-null    float64
 7   c_ChangePer  246 non-null    float64
dtypes: float64(7), object(1)
memory usage: 15.5+ KB


#### Index to column

In [48]:
vixData['Index_as_column'] = vixData.index
vixData

c_Date   c_Open   c_High    c_Low  c_Close  c_PrevClose  c_Change  \
0    01-Jan-2018  12.6700  13.6125  12.5450  13.3525      12.6700      0.68   
1    02-Jan-2018  13.3525  13.8425  12.6050  13.6850      13.3525      0.33   
2    03-Jan-2018  13.6850  13.7150  12.7650  13.6225      13.6850     -0.06   
3    04-Jan-2018  13.6225  13.7925  12.1825  13.4150      13.6225     -0.21   
4    05-Jan-2018  13.4150  13.4150  12.4200  13.1125      13.4150     -0.30   
..           ...      ...      ...      ...      ...          ...       ...   
241  24-Dec-2018  15.9925  17.1325  14.8975  15.7500      15.9925     -0.24   
242  26-Dec-2018  15.7500  17.4775  14.8075  15.9200      15.7500      0.17   
243  27-Dec-2018  15.9200  16.3750  12.5625  16.0725      15.9200      0.15   
244  28-Dec-2018  16.0725  16.0725  15.0150  15.2700      16.0725     -0.80   
245  31-Dec-2018  15.2700  16.1525  14.6500  16.0000      15.2700      0.73   

     c_ChangePer  Index_as_column  
0           5.39                0  
1           2.49                1  
2          -0.46                2  
3          -1.52                3  
4          -2.25                4  
..           ...              ...  
241        -1.52              241  
242         1.08              242  
243         0.96              243  
244        -4.99              244  
245         4.78              245  

[246 rows x 9 columns]

### Slice Rows

In [49]:
vixData[2:5] # Rows 2 to 5

c_Date   c_Open   c_High    c_Low  c_Close  c_PrevClose  c_Change  \
2  03-Jan-2018  13.6850  13.7150  12.7650  13.6225      13.6850     -0.06   
3  04-Jan-2018  13.6225  13.7925  12.1825  13.4150      13.6225     -0.21   
4  05-Jan-2018  13.4150  13.4150  12.4200  13.1125      13.4150     -0.30   

   c_ChangePer  Index_as_column  
2        -0.46                2  
3        -1.52                3  
4        -2.25                4

In [50]:
vixData[242:]   # Rows 242 onwards

c_Date   c_Open   c_High    c_Low  c_Close  c_PrevClose  c_Change  \
242  26-Dec-2018  15.7500  17.4775  14.8075  15.9200      15.7500      0.17   
243  27-Dec-2018  15.9200  16.3750  12.5625  16.0725      15.9200      0.15   
244  28-Dec-2018  16.0725  16.0725  15.0150  15.2700      16.0725     -0.80   
245  31-Dec-2018  15.2700  16.1525  14.6500  16.0000      15.2700      0.73   

     c_ChangePer  Index_as_column  
242         1.08              242  
243         0.96              243  
244        -4.99              244  
245         4.78              245

In [51]:
vixData[ : :-1]   #------- In reverse order

c_Date   c_Open   c_High    c_Low  c_Close  c_PrevClose  c_Change  \
245  31-Dec-2018  15.2700  16.1525  14.6500  16.0000      15.2700      0.73   
244  28-Dec-2018  16.0725  16.0725  15.0150  15.2700      16.0725     -0.80   
243  27-Dec-2018  15.9200  16.3750  12.5625  16.0725      15.9200      0.15   
242  26-Dec-2018  15.7500  17.4775  14.8075  15.9200      15.7500      0.17   
241  24-Dec-2018  15.9925  17.1325  14.8975  15.7500      15.9925     -0.24   
..           ...      ...      ...      ...      ...          ...       ...   
4    05-Jan-2018  13.4150  13.4150  12.4200  13.1125      13.4150     -0.30   
3    04-Jan-2018  13.6225  13.7925  12.1825  13.4150      13.6225     -0.21   
2    03-Jan-2018  13.6850  13.7150  12.7650  13.6225      13.6850     -0.06   
1    02-Jan-2018  13.3525  13.8425  12.6050  13.6850      13.3525      0.33   
0    01-Jan-2018  12.6700  13.6125  12.5450  13.3525      12.6700      0.68   

     c_ChangePer  Index_as_column  
245         4.78              245  
244        -4.99              244  
243         0.96              243  
242         1.08              242  
241        -1.52              241  
..           ...              ...  
4          -2.25                4  
3          -1.52                3  
2          -0.46                2  
1           2.49                1  
0           5.39                0  

[246 rows x 9 columns]

In [52]:
vixData[ : :20]   #------- Get every  20th row

c_Date   c_Open   c_High    c_Low  c_Close  c_PrevClose  c_Change  \
0    01-Jan-2018  12.6700  13.6125  12.5450  13.3525      12.6700      0.68   
20   30-Jan-2018  17.8875  18.0050  16.1500  16.4150      17.8875     -1.47   
40   28-Feb-2018  13.9225  14.4000  12.5250  13.8050      13.9225      0.00   
60   02-Apr-2018  15.7575  16.4500  15.1975  15.3475      15.7575     -0.41   
80   30-Apr-2018  12.0175  12.5525  12.0175  12.3625      12.0175      0.35   
100  29-May-2018  13.0550  13.8675  11.9750  13.0700      13.0550      0.02   
120  26-Jun-2018  12.5825  12.9700  12.3325  12.7975      12.5825      0.22   
140  24-Jul-2018  13.0050  13.0800  12.1475  12.4675      13.0050     -0.54   
160  23-Aug-2018  12.9025  13.1175   9.5300  12.7575      12.9025     -0.15   
180  24-Sep-2018  15.5350  17.8550  13.8025  17.4275      15.5350      1.89   
200  24-Oct-2018  19.0375  19.8100  17.7125  18.8800      19.0375     -0.16   
220  22-Nov-2018  19.5550  20.0025  17.0875  19.1600      19.5550     -0.40   
240  21-Dec-2018  14.3325  16.2300  12.9400  15.9925      14.3325      1.66   

     c_ChangePer  Index_as_column  
0           5.39                0  
20         -8.23               20  
40          0.00               40  
60         -2.60               60  
80          2.87               80  
100         0.11              100  
120         1.71              120  
140        -4.13              140  
160        -1.12              160  
180        12.18              180  
200        -0.83              200  
220        -2.02              220  
240        11.58              240

In [53]:
vixData[10:20:2]   #------- Alternative row between 10 and 20

c_Date   c_Open   c_High    c_Low  c_Close  c_PrevClose  c_Change  \
10  15-Jan-2018  13.7325  14.4750  11.8125  14.3050      13.7325      0.57   
12  17-Jan-2018  14.0850  14.4450  10.3450  13.8600      14.0850     -0.23   
14  19-Jan-2018  13.9600  14.1950  10.7500  13.9825      13.9600      0.02   
16  23-Jan-2018  15.3925  16.2975  14.1100  16.2250      15.3925      0.83   
18  25-Jan-2018  18.0400  18.2350  17.0350  17.5075      18.0400     -0.53   

    c_ChangePer  Index_as_column  
10         4.17               10  
12        -1.60               12  
14         0.16               14  
16         5.41               16  
18        -2.95               18

### Slice Columns

In [54]:
vixData['c_Close']   # Get column by name

0      13.3525
1      13.6850
2      13.6225
3      13.4150
4      13.1125
        ...   
241    15.7500
242    15.9200
243    16.0725
244    15.2700
245    16.0000
Name: c_Close, Length: 246, dtype: float64

In [55]:
vixData.c_Close.head()   # Get column by . operator and get just the top 5 values

0    13.3525
1    13.6850
2    13.6225
3    13.4150
4    13.1125
Name: c_Close, dtype: float64

### Slice by Rows and Columns

In [56]:
vixData[2:5][['c_Close', 'c_ChangePer']]  # Rows 2 to 5 and selected column

c_Close  c_ChangePer
2  13.6225        -0.46
3  13.4150        -1.52
4  13.1125        -2.25

In [57]:
vixData[['c_Close', 'c_ChangePer']][2:5]   # Selected column and rows 2 to 5 - returns same value

c_Close  c_ChangePer
2  13.6225        -0.46
3  13.4150        -1.52
4  13.1125        -2.25

### Basic Operations with Datasets

In [58]:
results = vixData['c_ChangePer'] * 100
results

0      539.0
1      249.0
2      -46.0
3     -152.0
4     -225.0
       ...  
241   -152.0
242    108.0
243     96.0
244   -499.0
245    478.0
Name: c_ChangePer, Length: 246, dtype: float64

### Adding a column

In [59]:
vixData['CalculatedChange'] = vixData['c_Close'] - vixData['c_PrevClose']

In [60]:
vixData.head(3)

c_Date   c_Open   c_High   c_Low  c_Close  c_PrevClose  c_Change  \
0  01-Jan-2018  12.6700  13.6125  12.545  13.3525      12.6700      0.68   
1  02-Jan-2018  13.3525  13.8425  12.605  13.6850      13.3525      0.33   
2  03-Jan-2018  13.6850  13.7150  12.765  13.6225      13.6850     -0.06   

   c_ChangePer  Index_as_column  CalculatedChange  
0         5.39                0            0.6825  
1         2.49                1            0.3325  
2        -0.46                2           -0.0625

### Removing a column

In [61]:
vixData = vixData.drop('CalculatedChange', 1)
#--- 2nd parameter: axis 1 = column
#--- drop returns a new object, so need to overwrite

In [62]:
vixData.head(3)

c_Date   c_Open   c_High   c_Low  c_Close  c_PrevClose  c_Change  \
0  01-Jan-2018  12.6700  13.6125  12.545  13.3525      12.6700      0.68   
1  02-Jan-2018  13.3525  13.8425  12.605  13.6850      13.3525      0.33   
2  03-Jan-2018  13.6850  13.7150  12.765  13.6225      13.6850     -0.06   

   c_ChangePer  Index_as_column  
0         5.39                0  
1         2.49                1  
2        -0.46                2

### Filtering rows - Based on a single or multiple conditions

In [63]:
vixData['c_ChangePer'] > 5

0       True
1      False
2      False
3      False
4      False
       ...  
241    False
242    False
243    False
244    False
245    False
Name: c_ChangePer, Length: 246, dtype: bool

In [64]:
changeFilter = vixData['c_ChangePer'] > 10

In [65]:
vixData[changeFilter]         #--- Can put the actual filter value here as well

c_Date   c_Open   c_High    c_Low  c_Close  c_PrevClose  c_Change  \
15   22-Jan-2018  13.9825  15.5900  12.0675  15.3925      13.9825      1.41   
17   24-Jan-2018  16.2250  18.4950  14.6400  18.0400      16.2250      1.82   
25   06-Feb-2018  16.0525  23.1575  16.0525  20.0150      16.0525      3.96   
179  21-Sep-2018  14.0050  16.9200  10.9825  15.5350      14.0050      1.53   
180  24-Sep-2018  15.5350  17.8550  13.8025  17.4275      15.5350      1.89   
192  11-Oct-2018  17.9075  20.8450  17.6275  20.5475      17.9075      2.64   
197  19-Oct-2018  17.9800  20.0525  17.4475  19.7875      17.9800      1.81   
240  21-Dec-2018  14.3325  16.2300  12.9400  15.9925      14.3325      1.66   

     c_ChangePer  Index_as_column  
15         10.08               15  
17         11.19               17  
25         24.68               25  
179        10.92              179  
180        12.18              180  
192        14.74              192  
197        10.05              197  
240        11.58              240

In [66]:
# Using multiple conditions    ---> DF[(filterCondition1) operator (filterCondition2)]
vixData[(vixData['c_ChangePer']>10) & (vixData['c_High']<20)]

c_Date   c_Open  c_High    c_Low  c_Close  c_PrevClose  c_Change  \
15   22-Jan-2018  13.9825  15.590  12.0675  15.3925      13.9825      1.41   
17   24-Jan-2018  16.2250  18.495  14.6400  18.0400      16.2250      1.82   
179  21-Sep-2018  14.0050  16.920  10.9825  15.5350      14.0050      1.53   
180  24-Sep-2018  15.5350  17.855  13.8025  17.4275      15.5350      1.89   
240  21-Dec-2018  14.3325  16.230  12.9400  15.9925      14.3325      1.66   

     c_ChangePer  Index_as_column  
15         10.08               15  
17         11.19               17  
179        10.92              179  
180        12.18              180  
240        11.58              240

In [67]:
round(vixData.c_Close).unique()

array([13., 14., 15., 16., 18., 20., 19., 17., 12., 21.])

In [68]:
set(round(vixData.c_Close))

{12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 18.0, 19.0, 20.0, 21.0}

### Getting a value from DF - .at, .iat, .loc, .iloc

In [69]:
#.at   --->   for labels. Important: even integers are treated as labels
#.iat  --->   for integer location

In [70]:
vixData.iat[3,2] 

13.7925

In [71]:
vixData.at[3,'c_High'] 

13.7925

### .loc and .iloc
#### loc is label-based, which means that you have to specify rows and columns based on their row and column labels. <br>iloc is integer position-based, so you have to specify rows and columns by their integer position values (0-based integer position).<br> <br>loc() method includes the last element of the range passed in it, unlike iloc(). <br>loc() can accept the boolean data unlike iloc() <br><br>loc[row_label, column_label]<br>iloc[row_position, column_position]

#### Differences

|  | loc | iloc |
| --- | --- | --- |
| **A value** | A single lable or integer  <br> eg. loc[A] or loc[1]| A single integer <br> eg. iloc[1] |
| **A list** | A list of labels <br> eg. loc[[A,B]] | A list of integers<br> eg. iloc[[1,2,3]] |
| **Slicing** | eg. loc[A:B] <br> both A and B are included  | eg. iloc[1:5] <br> 1 is included, 5 is excluded |
| **Conditions** | A bool series or list | A bool list |
| **Callable Function** | loc[lambda x: x[2]] | iloc[lambda x: x[2] |

### .loc() examples

In [72]:
vixData.loc[17, 'c_High']    # row with 17 index value

18.495

In [73]:
 # selecting range of rows from 2 to 5
display(vixData.loc[2 : 5])

c_Date   c_Open   c_High    c_Low  c_Close  c_PrevClose  c_Change  \
2  03-Jan-2018  13.6850  13.7150  12.7650  13.6225      13.6850     -0.06   
3  04-Jan-2018  13.6225  13.7925  12.1825  13.4150      13.6225     -0.21   
4  05-Jan-2018  13.4150  13.4150  12.4200  13.1125      13.4150     -0.30   
5  08-Jan-2018  13.1125  13.8550  11.8125  13.7350      13.1125      0.62   

   c_ChangePer  Index_as_column  
2        -0.46                2  
3        -1.52                3  
4        -2.25                4  
5         4.75                5

In [74]:
vixData.loc[:, 'c_Close']   # All rows

0      13.3525
1      13.6850
2      13.6225
3      13.4150
4      13.1125
        ...   
241    15.7500
242    15.9200
243    16.0725
244    15.2700
245    16.0000
Name: c_Close, Length: 246, dtype: float64

In [75]:
vixData.loc[:, 'c_High':'c_Close' ]

c_High    c_Low  c_Close
0    13.6125  12.5450  13.3525
1    13.8425  12.6050  13.6850
2    13.7150  12.7650  13.6225
3    13.7925  12.1825  13.4150
4    13.4150  12.4200  13.1125
..       ...      ...      ...
241  17.1325  14.8975  15.7500
242  17.4775  14.8075  15.9200
243  16.3750  12.5625  16.0725
244  16.0725  15.0150  15.2700
245  16.1525  14.6500  16.0000

[246 rows x 3 columns]

In [76]:
vixData.loc[vixData.c_Date=='24-Jan-2018']

c_Date  c_Open  c_High  c_Low  c_Close  c_PrevClose  c_Change  \
17  24-Jan-2018  16.225  18.495  14.64    18.04       16.225      1.82   

    c_ChangePer  Index_as_column  
17        11.19               17

In [77]:
vixData.loc[vixData.c_Date=='24-Jan-2018', 'c_High']

17    18.495
Name: c_High, dtype: float64

In [78]:
vixData.loc[lambda df: df.c_Close > 20, :]

c_Date   c_Open   c_High    c_Low  c_Close  c_PrevClose  c_Change  \
25   06-Feb-2018  16.0525  23.1575  16.0525  20.0150      16.0525      3.96   
189  08-Oct-2018  19.7325  21.7650  18.4775  20.1475      19.7325      0.42   
192  11-Oct-2018  17.9075  20.8450  17.6275  20.5475      17.9075      2.64   
198  22-Oct-2018  19.7875  21.6725  17.0800  21.3575      19.7875      1.57   
204  30-Oct-2018  19.8250  20.7725  19.5500  20.5025      19.8250      0.68   
221  26-Nov-2018  19.1600  20.5275  15.0175  20.4025      19.1600      1.24   
231  10-Dec-2018  18.5900  20.6450  16.8900  20.4375      18.5900      1.85   

     c_ChangePer  Index_as_column  
25         24.68               25  
189         2.10              189  
192        14.74              192  
198         7.93              198  
204         3.42              204  
221         6.48              221  
231         9.94              231

### .iloc() examples

In [79]:
vixData.iloc[17, 2]

18.495

In [80]:
vixData.iloc[[0, 2, 4, 7]]

c_Date   c_Open   c_High    c_Low  c_Close  c_PrevClose  c_Change  \
0  01-Jan-2018  12.6700  13.6125  12.5450  13.3525      12.6700      0.68   
2  03-Jan-2018  13.6850  13.7150  12.7650  13.6225      13.6850     -0.06   
4  05-Jan-2018  13.4150  13.4150  12.4200  13.1125      13.4150     -0.30   
7  10-Jan-2018  13.8475  14.2275  12.5175  14.0350      13.8475      0.19   

   c_ChangePer  Index_as_column  
0         5.39                0  
2        -0.46                2  
4        -2.25                4  
7         1.35                7

In [81]:
display(vixData.iloc[1 : 5, 2 : 5])

c_High    c_Low  c_Close
1  13.8425  12.6050  13.6850
2  13.7150  12.7650  13.6225
3  13.7925  12.1825  13.4150
4  13.4150  12.4200  13.1125

In [82]:
vixData.iloc[:, 4]   # All rows

0      13.3525
1      13.6850
2      13.6225
3      13.4150
4      13.1125
        ...   
241    15.7500
242    15.9200
243    16.0725
244    15.2700
245    16.0000
Name: c_Close, Length: 246, dtype: float64

In [83]:
# We get the error because iloc cannot accept a boolean Series. 
# It only accepts a boolean list. We can use the list() function to convert a Series into a boolean list.

vixData.iloc[vixData.c_Close > 20]

NotImplementedError: iLocation based boolean indexing on an integer type is not available

In [84]:
vixData.iloc[list(vixData.c_Close > 20)]

c_Date   c_Open   c_High    c_Low  c_Close  c_PrevClose  c_Change  \
25   06-Feb-2018  16.0525  23.1575  16.0525  20.0150      16.0525      3.96   
189  08-Oct-2018  19.7325  21.7650  18.4775  20.1475      19.7325      0.42   
192  11-Oct-2018  17.9075  20.8450  17.6275  20.5475      17.9075      2.64   
198  22-Oct-2018  19.7875  21.6725  17.0800  21.3575      19.7875      1.57   
204  30-Oct-2018  19.8250  20.7725  19.5500  20.5025      19.8250      0.68   
221  26-Nov-2018  19.1600  20.5275  15.0175  20.4025      19.1600      1.24   
231  10-Dec-2018  18.5900  20.6450  16.8900  20.4375      18.5900      1.85   

     c_ChangePer  Index_as_column  
25         24.68               25  
189         2.10              189  
192        14.74              192  
198         7.93              198  
204         3.42              204  
221         6.48              221  
231         9.94              231

In [85]:
vixData.loc[lambda df: [0,1], :]

c_Date   c_Open   c_High   c_Low  c_Close  c_PrevClose  c_Change  \
0  01-Jan-2018  12.6700  13.6125  12.545  13.3525      12.6700      0.68   
1  02-Jan-2018  13.3525  13.8425  12.605  13.6850      13.3525      0.33   

   c_ChangePer  Index_as_column  
0         5.39                0  
1         2.49                1

### create csv file

In [86]:
vixData.to_csv('updated_file.csv')

## Advanced Tips for Pandas

In [ ]:
import numpy as np
import pandas as pd

In [11]:
df = pd.DataFrame({
    "Team": ["RCB","CSK","MI","MI","CSK",np.nan,np.nan,"RCB"],
    "Player": [
       "Kohli","Dhoni","Sharma","Bhumrah","Jadeja","Uthappa","Maxwell","Karthik"
    ],
    "Score": [91, 92, np.nan, 84, np.nan, 70, 56, 89]
})
df

Team   Player  Score
0  RCB    Kohli   91.0
1  CSK    Dhoni   92.0
2   MI   Sharma    NaN
3   MI  Bhumrah   84.0
4  CSK   Jadeja    NaN
5  NaN  Uthappa   70.0
6  NaN  Maxwell   56.0
7  RCB  Karthik   89.0

#### Get the count for each value

In [2]:
df["Team"].value_counts()

RCB    2
MI     2
CSK    2
Name: Team, dtype: int64

#### Include the NaN as well in the count

In [3]:
df["Team"].value_counts(dropna=False)

RCB    2
MI     2
CSK    2
NaN    2
Name: Team, dtype: int64

#### Filling missing values by using other columns

In [5]:
df.loc[df["Team"].isna()==True, "Team"] = df["Player"]

In [6]:
df

Team   Player  Score
0      RCB    Kohli   91.0
1      CSK    Dhoni   92.0
2       MI   Sharma    NaN
3       MI  Bhumrah   84.0
4      CSK   Jadeja    NaN
5  Uthappa  Uthappa   70.0
6  Maxwell  Maxwell   56.0
7      RCB  Karthik   89.0

In [10]:
# use the fillna function directly
df["Team"].fillna(df["Player"], inplace=True)
df

Team   Player  Score
0      RCB    Kohli   91.0
1      CSK    Dhoni   92.0
2       MI   Sharma    NaN
3       MI  Bhumrah   84.0
4      CSK   Jadeja    NaN
5  Uthappa  Uthappa   70.0
6  Maxwell  Maxwell   56.0
7      RCB  Karthik   89.0

The values in the score column are integers but they are shown as floating point numbers. The reason is the missing values in this column.

In [12]:
df["Score"] = df["Score"].astype(pd.Int64Dtype())
df

Team   Player  Score
0  RCB    Kohli     91
1  CSK    Dhoni     92
2   MI   Sharma   <NA>
3   MI  Bhumrah     84
4  CSK   Jadeja   <NA>
5  NaN  Uthappa     70
6  NaN  Maxwell     56
7  RCB  Karthik     89

## Merge Dataframes

In [1]:
import pandas as pd

In [4]:
df1 = pd.DataFrame([
                    [1, "A"], [2,"B"]
                    ], columns = ["col1", "col2"])
print(df1)


df2 = pd.DataFrame([
                    ["A", 40], ["B", 30]
                    ], columns = ["col2", "col3"])
print(df2)

   col1 col2
0     1    A
1     2    B
  col2  col3
0    A    40
1    B    30


In [5]:
df_m = pd.merge(df1, df2, on="col2", how="inner")
print (df_m)

   col1 col2  col3
0     1    A    40
1     2    B    30


### Sort DataFrame

In [6]:
df_m.sort_values(by="col3")

col1 col2  col3
1     2    B    30
0     1    A    40

## Concatenating DataFrames

In [7]:
df1 = pd.DataFrame([[1, "A"], 
                    [2,"B"]
                    ], columns = ["col1", "col2"])
print(df1)


df2 = pd.DataFrame([["A", 40], 
                    ["B", 30]
                    ], columns = ["col3", "col4"])
print(df2)

   col1 col2
0     1    A
1     2    B
  col3  col4
0    A    40
1    B    30


In [9]:
df_c = pd.concat((df1, df2), axis=1)
print (df_c)

#axis = 1 stacks columns together.
#axis = 0 stacks rows together, provided column header match.

   col1 col2 col3  col4
0     1    A    A    40
1     2    B    B    30


### Rename columns

In [13]:
df_c = df_c.rename(columns={
                "col1":"c_1",
                "col2":"c_2",
                "col3":"c_3",
                "col4":"c_4"
            })
df_c

c_1 c_2 c_3  c_4
0    1   A   A   40
1    2   B   B   30

### Add a new column

In [14]:
df_c["c_new"] = df_c["c_4"] + 10
df_c

c_1 c_2 c_3  c_4  c_new
0    1   A   A   40     50
1    2   B   B   30     40

### Group By

In [15]:
df_1 = pd.DataFrame([[1, "A"],
                     [2, "A"],
                     [3, "B"],
                     [4, "B"],
                     [5, "A"]], columns = ["col1", "col2"])

df_1.groupby("col2").col1.sum()

col2
A    8
B    7
Name: col1, dtype: int64

### Apply function on a column

In [16]:
print(df_1)

   col1 col2
0     1    A
1     2    A
2     3    B
3     4    B
4     5    A


In [17]:
def foo(number):
    return number * 2

df_1["col3"] = df_1.col1.apply(foo)

print(df_1)

   col1 col2  col3
0     1    A     2
1     2    A     4
2     3    B     6
3     4    B     8
4     5    A    10


### Remove Duplicates rows

In [19]:
df_1 = pd.DataFrame([[1, "A"],
                     [2, "A"],
                     [3, "B"],
                     [3, "B"],
                     [2, "A"]], columns = ["col1", "col2"])

print(df_1)

   col1 col2
0     1    A
1     2    A
2     3    B
3     3    B
4     2    A


In [20]:
df_1.drop_duplicates()

col1 col2
0     1    A
1     2    A
2     3    B

### Count - find the frequency of each value in each column

In [23]:
df_1.col2.value_counts()

A    3
B    2
Name: col2, dtype: int64

In [24]:
df_1.shape

(5, 2)